cookie:
  expiry_days: 30
  key: some_signature_key
  name: some_cookie_name
credentials:
  usernames:
    eternal_sage:
      email: argamedevelop@gmail.com
      failed_login_attempts: 0
      logged_in: false
      name: Angel Rodriguez
      password: $2b$12$5ab/74GUrT2U6IL6NeA4cuoohH8oy8oMFJyDEwOt29ZhtfPR1AYZi
    jsmith:
      email: jsmith@gmail.com
      failed_login_attempts: 0
      logged_in: false
      name: John Smith
      password: $2b$12$tWBH8SHqa/Y9REN20CtZAuB6rrpsxEj8qJv7ZVlNwR0tWmcH9aIN.
    rbriggs:
      email: rbriggs@gmail.com
      failed_login_attempts: 0
      logged_in: false
      name: Rebecca Briggs
      password: $2b$12$XBWMmrofXtAzEr2KZFc90./8DwXwtO4F6pwAcB0pKIHxYo2iNzZ52
    whybless:
      email: ardatapro@gmail.com
      failed_login_attempts: 0
      logged_in: false
      name: Angel Rodriguez
      password: $2b$12$ue0pktK9E3M0MEVji5SnHOQPDDS6IrYASvMZLJnKAWlruM9Zkfk3y
pre-authorized:
  emails:
  - melsby@gmail.com
